"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  "let g:vundles=['general', 'git', 'programming', 'completion', 'ruby', 'python', 'misc', 'php', 'javascript', 'html']
  let g:vundles=['general', 'programming', 'git', 'python', 'misc', 'php', 'javascript', 'html']
  let g:neocomplcache_enable_at_startup = 1
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
  Bundle 'wakatime/vim-wakatime'
  Bundle 'vim-airline/vim-airline'
  Bundle 'vim-airline/vim-airline-themes'
  let g:airline_theme='violet'
endif

" Customize to your needs...

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
   silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
         \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
call plug#begin()
if has("python")
  Plug 'https://gitlab.com/code-stats/code-stats-vim.git'
  let g:codestats_api_key = 'SFMyNTY.YzJGcFoydHBiR3c9IyNNakF4.ICdCUkkSHD88FoxhBZVGtdjpaneTRbnBSXksE3YAssk'
  let g:airline_section_x = airline#section#create_right(['tagbar', 'filetype', '%{CodeStatsXp()}'])
endif
call plug#end()
